# Generated by Django 3.1.2 on 2020-10-22 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quiz')),
            ],
            options={
                'verbose_name': 'QuizSession',
                'verbose_name_plural': 'QuizSessions',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerInSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionanswered')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quizsession')),
            ],
            options={
                'verbose_name': 'QuestionAnswerInSession',
                'verbose_name_plural': 'QuestionAnswerInSessions',
            },
        ),
    ]
