# Generated by Django 3.1.2 on 2020-11-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201023_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='color',
            field=models.CharField(default='#3880ff', max_length=10),
            preserve_default=False,
        ),
    ]
